name: Publish Docker Images

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  build_frontend_image:
    name: Build Frontend Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Image
        run: |
          cd frontend/
          rm .npmrc 
          echo $'@dulliag:registry=https://npm.pkg.github.com\n//npm.pkg.github.com/:_authToken='$NPM_TOKEN >> .npmrc
          docker build --secret id=npm,src=.npmrc . -t ghcr.io/dulliag/w2g-frontend:${{ github.ref_name }}
          mkdir -p frontend_artifacts
          docker save ghcr.io/dulliag/w2g-frontend:${{ github.ref_name }} > frontend_artifacts/docker-image.tar
        env:
          DOCKER_BUILDKIT: 1
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Save Docker image
        uses: actions/upload-artifact@v2
        with:
          name: docker-frontend
          path: frontend/frontend_artifacts
          retention-days: 1

  build_backend_image:
    name: Build Backend Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Image
        run: |
          cd backend/
          docker build . -t ghcr.io/dulliag/w2g-backend:${{ github.ref_name }}
          mkdir -p backend_artifacts
          docker save ghcr.io/dulliag/w2g-backend:${{ github.ref_name }} > backend_artifacts/docker-image.tar
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Save Docker image
        uses: actions/upload-artifact@v2
        with:
          name: docker-backend
          path: backend/backend_artifacts
          retention-days: 1

  push_images:
    needs:
      - build_frontend_image
      - build_backend_image
    name: Push Images
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Frontend Image
        uses: actions/download-artifact@v2
        with:
          name: docker-frontend
          path: frontend/frontend_artifacts

      - name: Retrieve Backend Image
        uses: actions/download-artifact@v2
        with:
          name: docker-backend
          path: backend/backend_artifacts

      - name: Login
        run: |
          echo ${{ secrets.NPM_TOKEN }} | docker login ghcr.io -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push Frontend Image
        run: |
          cd frontend/frontend_artifacts
          docker load < docker-image.tar          
          docker push ghcr.io/dulliag/w2g-frontend:${{ github.ref_name }}

      - name: Push Backend Image
        run: |
          cd backend/backend_artifacts
          docker load < docker-image.tar          
          docker push ghcr.io/dulliag/w2g-backend:${{ github.ref_name }}

  cleanup:
    needs: push_images
    name: Cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Delete Frontend Artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: docker-frontend

      - name: Delete Backend Artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: docker-backend
